apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  annotations:
    app.ibm.com/hosting-deployable: mcm-policies/policies-Policy-policy-vulnerability
    app.ibm.com/hosting-subscription: mcm-policies/github-policies-subscription
    app.ibm.com/sync-source: subgbk8s-mcm-policies/github-policies-subscription
    policy.mcm.ibm.com/categories: SystemAndCommunicationsProtections
    policy.mcm.ibm.com/controls: VulnerbilityAdvisor
    policy.mcm.ibm.com/standards: NIST
  name: policy-vulnerability
  namespace: mcm-policies
spec:
  complianceType: musthave
  disabled: true
  namespaces:
    exclude:
    - kube-*
    include:
    - default
  policy-templates:
  - objectDefinition:
      apiVersion: policies.ibm.com/v1alpha1
      kind: VulnerabilityPolicy
      metadata:
        label:
          category: System-Integrity
        name: policy-vulnerability-example
      spec:
        namespaceSelector:
          exclude:
          - kube-system
          include:
          - default
          - kube-*
        remediationAction: inform
        severity: medium
  remediationAction: inform

---
piVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-vulnerability
  namespace: mcm-policies
placementRef:
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
  name: placement-policy-vulnerability
subjects:
- apiGroup: policy.mcm.ibm.com
  kind: Policy
  name: policy-vulnerability

---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-vulnerability
  namespace: mcm-policies
spec:
  clusterLabels:
    matchExpressions:
    - key: cloud
      operator: In
      values:
      - MyDataCenter2
      - MyDataCenter1
